export const cartItem: string;
export const cartItemImg: string;
export const cartItemText: string;
export const cartItemTitle: string;
export const cartItemDelete: string;
export const cartItemSubtitle: string;
export const cartItemPrice: string;
export const cartItemQty: string;
export const cartItemSelect: string;
